name: Build

on: [push, pull_request]

jobs:
  build-debug:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: pip install conan

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build
      run: cmake --build .build/

    - name: Test
      run: |
        cd .build/
        ctest .
  
  build-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: pip install conan

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build
      run: cmake --build .build/

    - name: Upload Artifact to Github
      uses: actions/upload-artifact@v2
      with:
        name: Juicy Renderer Release
        path: |
          .build/app/Release/app.exe
          bin/